Repository ambianic/ambianic-edge, pull requests merged in 2020-11, with the labels that each got.

#222 feat: config api refactor
  config.local.yaml
  config.yaml
  src/ambianic/__init__.py
  src/ambianic/config_mgm/__init__.py
  src/ambianic/config_mgm/config_diff.py
  src/ambianic/config_mgm/configuration_manager.py
  src/ambianic/config_mgm/fileutils.py
  src/ambianic/config_util.py
  src/ambianic/pipeline/interpreter.py
  src/ambianic/pipeline/store.py
  src/ambianic/server.py
  src/ambianic/webapp/flaskr.py
  src/ambianic/webapp/server/config_sources.py
  src/ambianic/webapp/server/samples.py
  src/setup.cfg
  tests/config_mgm/test-sources.yaml
  tests/config_mgm/test_config_api_source.py
  tests/config_mgm/test_config_diff.py
  tests/config_mgm/test_config_events.py
  tests/pipeline/test_interpreter.py
  tests/pipeline/test_interpreter_more.py
  tests/pipeline/test_pipeline_server.py
  tests/test-config-secrets.yaml
  tests/test-config.yaml
  tests/test_config.py
  tests/test_flaskr.py
  tests/test_startup.py
Labels: size/XXL

#223 bugfix: handle corrupted yaml
  src/ambianic/webapp/server/samples.py
  tests/test_samples.py
Labels: size/M

#225 fix: remove ca install on start
  build/ambianic-docker-entrypoint.sh
Labels: size/S

#226 feat: fully automate dev setup with Gitpod
  .gitpod.yml
  README.md
  config.yaml
Labels: size/XS
