Repository ambianic/ambianic-edge, pull requests merged in 2020-12, with the labels that each got.

#227 chore
  .gitpod.Dockerfile
  .gitpod.yml
  .theia/launch.json
  .theia/settings.json
  .travis.yml
  build/install_requirements.sh
  build/requirements.txt
  src/setup.cfg
  tests/pipeline/ai/test_object_detect.py
  tests/run-tests.sh
Labels: size/L

#229 feat: add label filter config option for object detection
  config.yaml
  src/ambianic/pipeline/ai/image_detection.py
  tests/pipeline/ai/person-couch.jpg
  tests/pipeline/ai/test_object_detect.py
  tests/pipeline/test_interpreter.py
Labels: enhancement

#239 fix: migrate ci from travis to github
  .github/workflows/main.yml
  .travis.yml
  README.md
  build/ambianic-test.sh
  build/ci-build-job.sh
Labels: size/L

#240 fix: release stage
  .github/workflows/main.yml
  build/ci-build-job.sh
Labels: size/XS

#241 fix: release stage
  .github/workflows/main.yml
  build/ci-build-job.sh
Labels: size/XS

#242 fix: release
  .github/workflows/main.yml
Labels: size/S

#243 fix: release
  .github/workflows/main.yml
Labels: size/S

#244 fix: release
  .github/workflows/main.yml
Labels: size/XS

#246 fix: update default config
  .github/workflows/main.yml
  config.yaml
  src/ambianic/pipeline/ai/fall_detect.py
  src/ambianic/pipeline/interpreter.py
Labels: size/M

#249 fix: pose engine
  config.yaml
  src/ambianic/pipeline/ai/fall_detect.py
  src/ambianic/pipeline/ai/pose_engine.py
Labels: size/M

#250 fix: store element
  build/CHANGELOG.md
  src/ambianic/pipeline/store.py
  tests/pipeline/test_store.py
Labels: size/L

#253 fix: fall detection
  .gitpod.yml
  CHANGELOG.md
  src/ambianic/pipeline/ai/fall_detect.py
  src/ambianic/pipeline/ai/image_detection.py
  src/ambianic/pipeline/ai/pose_engine.py
  tests/pipeline/ai/test_fall_detect.py
Labels: size/L

#255 fix: fall detection edge case
  .gitpod.yml
  src/ambianic/pipeline/ai/fall_detect.py
  tests/pipeline/ai/test_fall_detect.py
Labels: size/S

#266 fix: fall detection tests
  tests/pipeline/ai/test_fall_detect.py
Labels: size/XS

#268 fix: codecov upload from ci
  build/ambianic-test.sh
  build/ci-test-job.sh
  tests/run-tests.sh
Labels: size/M

#269 docs: create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/M

#251 fix: configuration bug fixes
  src/ambianic/__init__.py
  src/ambianic/config_util.py
  src/ambianic/pipeline/ai/inference.py
  src/ambianic/server.py
  tests/secrets.yaml
  tests/test-config-secrets.yaml
  tests/test-config.yaml
  tests/test-config2.yaml
  tests/test_config.py
  tests/test_startup.py
Labels: size/L

#271 fix: release script
  build/ci-prep-release-job.sh
Labels: size/XS

#276 feature: added notification
  build/requirements.txt
  config.local.yaml
  config.yaml
  src/ambianic/__init__.py
  src/ambianic/notification.py
  src/ambianic/pipeline/store.py
  src/ambianic/server.py
  tests/pipeline/test_notify.py
  tests/test-config-secrets.yaml
Labels: enhancement, size/L
