Repository ambianic/ambianic-edge, pull requests merged in 2021-02, with the labels that each got.

#295 fix: fall-detection bug #294
  tests/pipeline/ai/test_fall_detect.py
Labels: size/XS

#298 fix: debug issue #294
  tests/pipeline/ai/test_fall_detect.py
Labels: size/S

#297 fix: search for timeline event in a flat dir only
  .gitpod.Dockerfile
  .theia/settings.json
  CHANGELOG.md
  src/ambianic/webapp/server/samples.py
Labels: size/S

#302 fix: adjust default confidence threshold for fall detection
  CHANGELOG.md
  build/requirements.txt
  src/ambianic/pipeline/ai/fall_detect.py
Labels: size/S

#306 fix: debug logging issues; closes #257; closes #305
  .theia/settings.json
  config.yaml
  src/ambianic/logger.py
  src/ambianic/pipeline/ai/fall_detect.py
  tests/test_config.py
  tests/test_logger.py
Labels: size/L

#307 fix: fall detection confidence_threshold propagation
  CHANGELOG.md
  src/ambianic/pipeline/ai/fall_detect.py
  src/ambianic/pipeline/ai/inference.py
  src/ambianic/pipeline/ai/pose_engine.py
  tests/pipeline/ai/test_fall_detect_more.py
Labels: size/L

#308 feat: introduced single sourcing for edge version
  .gitignore
  .theia/settings.json
  build/requirements.txt
  src/ambianic/__init__.py
  src/ambianic/webapp/flaskr.py
  tests/test_flaskr.py
Labels: size/M

#310 build: enable github security analysis
  .github/workflows/codeql-analysis.yml
Labels: size/M

#309 fix: fall detection debug info
  .gitignore
  .lgtm.yml
  .theia/settings.json
  CHANGELOG.md
  src/ambianic/logger.py
  src/ambianic/pipeline/ai/fall_detect.py
  src/ambianic/pipeline/ai/pose_engine.py
  src/ambianic/pipeline/avsource/picam.py
  src/ambianic/server.py
  tests/pipeline/ai/test_fall_detect.py
  tests/pipeline/ai/test_fall_detect_more.py
  tests/pipeline/avsource/test_avsource_http.py
  tests/test_logger.py
Labels: size/L

#314 fix: separate inference output formatting for each detection model; closes #254
  peerjs-config.yaml
  src/ambianic/pipeline/ai/face_detect.py
  src/ambianic/pipeline/ai/fall_detect.py
  src/ambianic/pipeline/ai/image_boundingBox_detection.py
  src/ambianic/pipeline/ai/object_detect.py
  src/ambianic/pipeline/ai/pose_engine.py
  src/ambianic/pipeline/store.py
  tests/pipeline/ai/test_face_detect.py
  tests/pipeline/ai/test_fall_detect.py
  tests/pipeline/ai/test_fall_detect_more.py
  tests/pipeline/ai/test_object_detect.py
  tests/pipeline/avsource/test_avsource.py
  tests/pipeline/avsource/test_avsource_http.py
  tests/pipeline/test_notify.py
  tests/pipeline/test_store.py
Labels: size/XL

#329 fix: revert #314; see #330 for details; separate inference output formatting for each detection model; closes #254"
  peerjs-config.yaml
  src/ambianic/pipeline/ai/face_detect.py
  src/ambianic/pipeline/ai/fall_detect.py
  src/ambianic/pipeline/ai/image_boundingBox_detection.py
  src/ambianic/pipeline/ai/object_detect.py
  src/ambianic/pipeline/ai/pose_engine.py
  src/ambianic/pipeline/store.py
  tests/pipeline/ai/test_face_detect.py
  tests/pipeline/ai/test_fall_detect.py
  tests/pipeline/ai/test_fall_detect_more.py
  tests/pipeline/ai/test_object_detect.py
  tests/pipeline/avsource/test_avsource.py
  tests/pipeline/avsource/test_avsource_http.py
  tests/pipeline/test_notify.py
  tests/pipeline/test_store.py
Labels: size/XL

#332 fix: separate inference output formatting for each detection model; [issues #330, #254]
  peerjs-config.yaml
  src/ambianic/pipeline/ai/face_detect.py
  src/ambianic/pipeline/ai/fall_detect.py
  src/ambianic/pipeline/ai/image_boundingBox_detection.py
  src/ambianic/pipeline/ai/object_detect.py
  src/ambianic/pipeline/ai/pose_engine.py
  src/ambianic/pipeline/store.py
  tests/pipeline/ai/test_face_detect.py
  tests/pipeline/ai/test_fall_detect.py
  tests/pipeline/ai/test_fall_detect_more.py
  tests/pipeline/ai/test_object_detect.py
  tests/pipeline/avsource/test_avsource.py
  tests/pipeline/avsource/test_avsource_http.py
  tests/pipeline/test_notify.py
  tests/pipeline/test_store.py
Labels: size/XXL

#333 fix: temporary solution to manage yaml.dump() encoding issue; closes #330
  src/ambianic/pipeline/store.py
  src/ambianic/pipeline/timeline.py
  src/ambianic/webapp/server/samples.py
  tests/pipeline/avsource/test_images_video.avi
  tests/test_samples.py
Labels: size/M
